# Generated by Django 2.1.1 on 2019-06-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveIntegerField()),
                ('tipo_vehiculo', models.CharField(max_length=10)),
                ('por_hora', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'tarifa',
                'ordering': ['anno'],
            },
        ),
    ]
