# Generated by Django 2.2.2 on 2019-07-02 02:31

from django.db import migrations, models
import parqueaderos.models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='anno',
            field=models.PositiveIntegerField(default=parqueaderos.models.default_id),
        ),
        migrations.AlterUniqueTogether(
            name='tarifa',
            unique_together={('anno', 'tipo_vehiculo')},
        ),
    ]
