# Generated by Django 2.2.2 on 2019-07-02 04:01

from django.db import migrations, models
import django.db.models.deletion
import parqueaderos.models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0002_auto_20190701_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='anno',
            field=models.PositiveIntegerField(default=parqueaderos.models.default_id, verbose_name='año'),
        ),
        migrations.CreateModel(
            name='EntradaVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('placa', models.CharField(max_length=6)),
                ('tarifa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parqueaderos.Tarifa')),
            ],
            options={
                'verbose_name': 'tarifa',
                'ordering': ['fecha_ingreso'],
                'unique_together': {('placa', 'fecha_ingreso')},
            },
        ),
    ]
