# Generated by Django 2.2.2 on 2019-07-03 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0003_auto_20190701_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradavehiculo',
            options={'ordering': ['fecha_ingreso'], 'verbose_name': 'entrada vehiculo'},
        ),
    ]
