# Generated by Django 2.2.2 on 2019-07-02 02:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usuario_identificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(default=accounts.models.default_id, max_length=15, primary_key=True, serialize=False),
        ),
    ]
