# Generated by Django 2.2.2 on 2019-07-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190701_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
